community/community/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('', include('userprofile.urls')),
]

community/forum/urls.py
from django.urls import path
from . import views
app_name = 'forum'
urlpatterns = [
    path('', views.home, name='home'),
  
]

community/userprofile/urls.py
from django.urls import path
from . import views

app_name="userprofile"
urlpatterns = [
    path('',views.home, name='home'),
    path('register/',views.userRegistration, name='register'),

]

community/forum/models.py
from django.db import models

# Create your models here.

community/userprofile/models.py
from django.db import models

# Create your models here.

community/userprofile/forms.py
from django.contrib.auth.models import User
from django import forms 
from django.contrib.auth.forms import UserCreationForm



class UserRegistration(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=['username', 'email', 'password1', 'password2']

community/forum/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'forum/index.html')

community/userprofile/views.py
from django.shortcuts import redirect, render
from .forms import UserRegistration
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages



# Create your views here.
def home(request):
    return render(request, 'userprofile/base.html')

def userRegistration(request):
    form = UserRegistration()
    if request.method=='POST':
        form=UserRegistration(request.POST)
        if form.is_valid():
            
            form.save()
            username=form.cleaned_data.get('username')
            messages.info(request, username+ 'your account is created, login to continue')
            return redirect('userprofile:login')
        

    context={'form':form}
    return render(request, 'userprofile/register.html', context)

def userLogin(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('forum:home')
        else:
            messages.info(request, 'username or password is incorrect')

    return render(request, 'userprofile/login.html')

community/forum/templates/forum/index.html
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-lg-offset-0">
                <div class="card-body">
                        <h1 class="card-title">Thread Listing </h1>
                </div>

                    <div class="row">
                        <div class="col-lg-3">
                            <a href="#newModal" data-toggle="modal" class="btn btn-primary" title="Add Thread">
                                 Add Thread
                            </a>
                        </div>
                    </div>

                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Last Post</th>
                        <th>Reply</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><a href="" style="font-size: 18px;" class="blue">title</a></td>
                        <td> description </td>
                        <td> date </td>
                        <td><a href=""> Reply</a></td>
                        
                    </tr>
                    </tbody>
                  </table>


    <div class="modal fade" id="newModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form action="" method="POST" role="form">
                        <div class="form-group">
                            <label for="name">Thread Name</label>
                            <br>
                                title
                        </div>
                        <div class="form-group" >
                            <label for="description">Description</label>
                            <br>
                                description
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    

community/forum/templates/forum/thread.html
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-lg-offset-0">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="card-body">
                        <a href="" class="btn btn-secondary">
                            Back to Threads 
                        </a>
                    </div>
                    </div>
                </div>

                <div class="row pad">
                    <div class="col-lg-12">
                        <div class="panel panel-primary">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="card-body">
                                    <div class="col-lg-12">
                                        <p style="font-size: 50px;" class="card-title">title</p> 
                                        <p>username</p>
                                    </div>
                                    <div class="col-lg-12">
                                        <p style="font-size: 30px;" class="card-text">description</p>
                                    </div>
                                </div>

                                    <div class="col-lg-12">
                                        <br />  
                                        date_created

                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>

                <h3 class="">Replies &mdash; ( total )</h3>

                    <div class="card">
                        <div class="card-body">
                        <div class="panel panel-primary reply" id="r1" style="border-radius: 10px;">
                            <div class="panel-body">
                                <div class="row reply">
                                    <div class="col-lg-9">
                                        <div class="reply-msg">
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="reply-details">
                                            date_created <br>
                                                    username
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <br>

                <div class="row pad">
                    <div class="col-lg-12 pad">
                        <div class="panel panel-primary">
                            <div class="panel-body pad" id="_reply">
                                <form action="" method="POST" role="form" id="theForm">
                                        {% csrf_token %}
                                        <div class="card-body">
                                    <div style="width: 100%;"> 
                                    message    
                                    </div>
                                
                                    <button 
                                        type="submit" 
                                        class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                                </form>
                            </div>
                            <div class="card-body"> 
                                <p class="card-text">You can not reply. Please Login to reply.</p>
                               <a class="btn btn-link" href="">Login</a>
                            </div>
                        </div>
                    </div>
                </div>

        </div>
    </div>
</div>

community/userprofile/templates/userprofile/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Forum</title>
</head>
<body>
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="">Forum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="">Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="">Profile</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="">Logout</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile:register' %}">Register</a>
            </li>

              
            </div>
    </nav>
      <hr>
    {% block content %}

      {% endblock %}


        <hr>
               
      <footer>
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    Copyright &copy; All rights reserved.
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

community/userprofile/templates/userprofile/login.html
{% extends 'userprofile/base.html' %}

{% block content %}


        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-lg-offset-4" id="loginBlock">
                    
                    <div class="logo">
        
                    </div>

                    <div class="pageTitle">Login</div>

                    <div class="row pad">
                        <div class="col-lg-10 col-lg-offset-1">
                            <form action="" method="POST" role="form">
                                <input type="text" name="username" placeholder="username">
                                <input type="password" name="password" placeholder="password">
                                <input class="btn btn-success" type="submit" value="Login">
                        <div class="card-body">

                            </div>
                            
                            </form>
                        </div>
                    </div>

            </div>
        </div>
    </div>

    {% endblock %}

community/userprofile/templates/userprofile/profile.html
{% extends 'userprofile/base.html' %}

{% block content %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-lg-offset-0">

                    <!-- display the page title and the number of threads we got from the database -->

                    <div class="row pad">
                        <div class="col-lg-12">
                            <div class="panel panel-primary">
                                <div class="card-body">
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        Email: <strong class="float-right"></strong>
                                    </li>
                                    <li class="list-group-item">
                                        Username: <strong class="float-right"></strong>
                                    </li>
                                    <li class="list-group-item">
                                        Number of Posts: <strong class="float-right"></strong>
                                    </li>
                                </ul>
                            </div>
                            </div>
                        </div>
                        
                        </div>
                    </div>


            </div>
        </div>
    </div>

    {% endblock %}

community/userprofile/templates/userprofile/register.html
{% extends 'userprofile/base.html' %}

{% block content %}   
   
   <div class="container">
    <div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div style="color: red;"> errors </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>

{% endblock %}